Adding post resume test data
redhat-beyond/ResuMe pull request #103
Opened 2022-04-16 20:39 UTC by MatanP12

- Adding migrations file to add 2 resumes
- Adding migrations file to add 2 comments
- Adding migration files to add 4 rating
- Adding several CV to files

fix #57

2022-04-17 12:43 UTC, TomerNewmanPrograms submitted a review, later dismissed
LGTM

2022-04-17 15:42 UTC, TomerNewmanPrograms requested changes

2022-04-17 15:42 UTC, TomerNewmanPrograms commented on posts/migrations/0006_add_resume_test_data.py
> +    def generate_rersume_test_data(apps, schema_editor):
Did you mean `resume` ?

2022-04-17 17:02 UTC, MatanP12 commented on posts/migrations/0006_add_resume_test_data.py
> +    def generate_rersume_test_data(apps, schema_editor):
You are right, Done 😄

2022-04-18 21:39 UTC, TomerNewmanPrograms submitted a review, later dismissed
LGTM

2022-04-20 08:08 UTC, yulisuliman approved these changes
Looks good!

2022-04-20 17:35 UTC, natifridman approved these changes

2022-04-20 17:52 UTC, yulisuliman approved these changes

2022-04-20 18:37 UTC, TomerNewmanPrograms approved these changes

2022-04-21 07:44 UTC, natifridman approved these changes

2022-04-21 07:44 UTC, merged