Adding Base template and about template
redhat-beyond/ResuMe pull request #77
Opened 2022-04-07 18:35 UTC by OmerCS8

- Adding a base template with the main menu that connects to all views.
- Adding template fo the 'about' page
- Adding CSS for base and about
fix #76
Depends on #72

2022-04-08 11:11 UTC, TomerNewmanPrograms requested changes

2022-04-08 11:11 UTC, TomerNewmanPrograms commented on static/styles/main.css
> +
Should be here a newline

2022-04-10 14:40 UTC, OmerCS8 commented on static/styles/main.css
> +
Why? 170 is a blank line.

2022-04-10 14:47 UTC, TomerNewmanPrograms commented on static/styles/main.css
> +
Its ok now

2022-04-10 14:49 UTC, TomerNewmanPrograms submitted a review, later dismissed

2022-04-11 16:18 UTC, yulisuliman approved these changes

2022-04-11 19:53 UTC, MatanP12 approved these changes
LGTM

2022-04-12 11:41 UTC, AlonShakaroff submitted a review, later dismissed
LGTM

2022-04-12 15:32 UTC, natifridman commented
@OmerCS8 Is there any reason why some of the CSS files are in the `static` folder in the root folder and some are under `posts/static`?

2022-04-12 15:51 UTC, OmerCS8 commented
> @OmerCS8 Is there any reason why some of the CSS files are in the `static` folder in the root folder and some are under `posts/static`?

Yes, the CSS file that in the `root/static` folder belongs to `base.html`, and therefore all of the apps are using it.

2022-04-13 06:53 UTC, yulisuliman submitted a review, later dismissed

2022-04-13 06:57 UTC, TomerNewmanPrograms approved these changes

2022-04-13 06:58 UTC, MatanP12 approved these changes
LGTM

2022-04-13 07:34 UTC, natifridman requested changes

2022-04-13 07:34 UTC, natifridman commented on static/styles/main.css
> + */
Please remove commented code

2022-04-13 07:39 UTC, OmerCS8 commented on static/styles/main.css
> + */
Done 👍

2022-04-13 07:41 UTC, TomerNewmanPrograms approved these changes
LGTm

2022-04-13 07:41 UTC, yulisuliman submitted a review, later dismissed

2022-04-13 07:43 UTC, AlonShakaroff submitted a review, later dismissed
LGTM

2022-04-13 07:43 UTC, MatanP12 submitted a review, later dismissed
LGTM

2022-04-13 08:57 UTC, TomerNewmanPrograms approved these changes
LGTM

2022-04-13 09:24 UTC, AlonShakaroff approved these changes

2022-04-13 09:28 UTC, yulisuliman approved these changes

2022-04-13 10:55 UTC, natifridman approved these changes

2022-04-13 10:56 UTC, yulisuliman commented
@OmerCS8  Please squash all commit into one

2022-04-13 11:19 UTC, merged