Setting up Flake8
redhat-beyond/ResuMe pull request #9
Opened 2022-03-03 16:47 UTC by MatanP12

- Installing Flake8 to the Vagrant VM.
- Adding Flake8 as GitHub Action.

Issue: #5

2022-03-03 17:47 UTC, OmerCS8 approved these changes
LGTM

2022-03-03 18:37 UTC, TomerNewmanPrograms approved these changes
Looks Ok

2022-03-03 20:05 UTC, MatanP12 commented
> You have linked the PR to itself, it should be fix #5

My bad, fixed.

2022-03-06 07:39 UTC, natifridman requested changes

2022-03-06 07:39 UTC, natifridman commented on .github/workflows/flake8.yml
> +          run: pipenv run flake8 --max-line-length 120
YAML is an indentation sensitive language. Please use 2 spaces here and not a tab or 4 spaces

2022-03-06 11:25 UTC, natifridman approved these changes
Approved. Please squash your commits

2022-03-06 12:12 UTC, natifridman approved these changes

2022-03-06 12:12 UTC, merged